# Generated by Django 2.2.5 on 2020-02-06 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brd_id', models.IntegerField(primary_key=True, serialize=False)),
                ('brd_name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'BRAND',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Common',
            fields=[
                ('com_id', models.IntegerField(primary_key=True, serialize=False)),
                ('com_name', models.CharField(blank=True, max_length=20, null=True)),
                ('com_img', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'COMMON',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prd_id', models.IntegerField(primary_key=True, serialize=False)),
                ('prd_name_shop', models.CharField(blank=True, max_length=50, null=True)),
                ('prd_url', models.CharField(blank=True, max_length=100, null=True)),
                ('prd_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('prd_price', models.CharField(blank=True, max_length=20, null=True)),
                ('prd_discount', models.CharField(blank=True, max_length=20, null=True)),
                ('prd_shipping', models.CharField(blank=True, max_length=20, null=True)),
                ('prd_benefit', models.CharField(blank=True, max_length=100, null=True)),
                ('prd_gift', models.CharField(blank=True, max_length=100, null=True)),
                ('rev_avg', models.FloatField(blank=True, null=True)),
                ('rev_cnt', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PRODUCT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.IntegerField(primary_key=True, serialize=False)),
                ('review_rating', models.FloatField(blank=True, null=True)),
                ('review_title', models.CharField(blank=True, max_length=100, null=True)),
                ('review_text', models.CharField(blank=True, max_length=500, null=True)),
                ('review_date', models.CharField(blank=True, max_length=30, null=True)),
                ('review_user_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'REVIEW',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shop_id', models.IntegerField(primary_key=True, serialize=False)),
                ('shop_name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'SHOP',
                'managed': False,
            },
        ),
    ]
