# Generated by Django 2.2.5 on 2020-02-07 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brd_id', models.IntegerField(primary_key=True, serialize=False)),
                ('brd_name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'brand',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Common',
            fields=[
                ('com_id', models.IntegerField(primary_key=True, serialize=False)),
                ('com_name', models.CharField(blank=True, max_length=100, null=True)),
                ('com_img', models.CharField(blank=True, max_length=1000, null=True)),
                ('brd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.Brand')),
            ],
            options={
                'db_table': 'common',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prd_id', models.AutoField(primary_key=True, serialize=False)),
                ('prd_name_shop', models.CharField(blank=True, max_length=200, null=True)),
                ('prd_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('prd_desc', models.CharField(blank=True, max_length=2000, null=True)),
                ('prd_price', models.CharField(blank=True, max_length=20, null=True)),
                ('prd_discount', models.CharField(blank=True, max_length=100, null=True)),
                ('prd_shipping', models.CharField(blank=True, max_length=100, null=True)),
                ('prd_benefit', models.CharField(blank=True, max_length=100, null=True)),
                ('prd_gift', models.CharField(blank=True, max_length=100, null=True)),
                ('rev_avg', models.FloatField(blank=True, null=True)),
                ('rev_cnt', models.IntegerField(blank=True, null=True)),
                ('com', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.Common')),
            ],
            options={
                'db_table': 'product',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shop_id', models.IntegerField(primary_key=True, serialize=False)),
                ('shop_name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'shop',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_rating', models.FloatField(blank=True, null=True)),
                ('review_title', models.CharField(blank=True, max_length=100, null=True)),
                ('review_text', models.CharField(blank=True, max_length=2000, null=True)),
                ('review_date', models.CharField(blank=True, max_length=30, null=True)),
                ('review_userid', models.CharField(blank=True, max_length=20, null=True)),
                ('prd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.Product')),
            ],
            options={
                'db_table': 'review',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.Shop'),
        ),
    ]
