# Generated by Django 2.2.5 on 2020-02-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prd_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
